---
- hosts: all
  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World
    - name: Print message again
      debug:
        msg: installing nginx
    - name: install the latest version of Apache
      yum:
        name: httpd
        state: latest
