---
- hosts: all
  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible World

    - name: Print message
      debug:
	msg: Hello installing nginx

    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes

    - name: Print message
      debug:
	msg: nginx installed

